MC-5244: Added changes to have resizable root volume
cloud-ca/docker-machine-driver-cloudca pull request #6
Opened 2017-05-17 18:19 UTC by franzpgarcia

2017-05-18 13:54 UTC, prollynomial requested changes

2017-05-18 13:54 UTC, prollynomial commented on cloudca.go
> +		rootDiskSizeInGb, _ := strconv.Atoi(d.RootDiskSizeInGb)
Shouldn't an error be returned if `RootDiskSizeInGb` can't be converted?

2017-05-24 17:26 UTC, franzpgarcia commented on cloudca.go
> +		rootDiskSizeInGb, _ := strconv.Atoi(d.RootDiskSizeInGb)
done

2017-05-25 15:17 UTC, prollynomial approved these changes
LGTM

2017-05-25 17:26 UTC, merged